[package]
name = "rtree-2d"
version = "0.1.0"
authors = ["Titus Tienaah <titus.intdxdt@gmail.com>"]
edition = "2018"

[dependencies]
rstar = "0.5.1"
[dev-dependencies]
bbox-2d = { git="https://github.com/intdxdt/bbox-2d", branch="master"}
geom-2d = { git="https://github.com/intdxdt/geom-2d", branch="master"}
